export const constants: any = {
	KEY_CODES: {
		Enter: 13,
		ControlCharacterMax: 31,
		FunctionKeyStart: 112,
		FunctionKeyEnd: 123,
		ArrowKeyLeft: 37,
		ArrowKeyUp: 38,
		ArrowKeyRight: 39,
		ArrowKeyDown: 40,
		Delete: 127,
		Space: 32,
		NumLock: 144,
		ContextMenu: 93,
		PageUp: 33,
		PageDown: 34,
		Home: 36,
		End: 35,
		Insert: 45,
	},
	IS_EMPTY_TEXT: () => null || undefined || "",
};
